### PR TITLE
Use ContainerPilot 3.3.0 and Consul 0.9.0

### PR DESCRIPTION
**Pull request by lucj**
Start modifications to init the move to ContainerPilot v3 :)

### CODE REVIEW

**Comment by lucj** [comment]
A new job running mongodump is run if DUMP env variable is set.
Additional functions (backup and upload) have been added to manage.py.

TO DO / FIX
- [ ] the backup function is triggered the first time but it seems something is preventing it from being triggered afterward. A first backup is done (small one as it only contains initial users)

```
-rw-r--r-- 1 root root  110 Aug  4 14:29 dump-2017-08-04T14:29:33.139365.gz
srwx------ 1 root root    0 Aug  4 14:29 mongodb-27017.sock
-rw-r--r-- 1 root root   36 Aug  4 14:29 mongodb-session
```

And then

```
ESC[36mdb_1             |ESC[0m time="2017-08-04T14:31:32Z" level=debug msg="interval expired but restart not permitted: backup"
ESC[36mdb_1             |ESC[0m time="2017-08-04T14:31:32Z" level=debug msg="event: {Stopping backup}"
ESC[36mdb_1             |ESC[0m time="2017-08-04T14:31:32Z" level=debug msg="event: {Stopped backup}"
```

- [ ] cannot upload dump to Manta, seems to be linked with the usage of put_object
- [ ] in order not to upload the ssh private key, use MANTA_TLS_INSECURE flag (is it the way to go ?)

**Comment by lucj** [comment]
Checking the DUMP_INTERVAL env var in order to add the *backup* job and set its inverval key with that value.

```
db:
    image: autopilotpattern/mongodb
    environment:
      - REPLICASET=testrs
      - CONSUL_AGENT=true
      - DUMP_INTERVAL=6h
      - LOG_LEVEL=DEBUG
      - MANTA_USER=...
      - MANTA_KEY_ID=...
    restart: always
```

**Comment by ptariche** [comment]
@geek

**Comment by geek** [comment]
@lucj are the remaining items on your checklist complete? LGTM, wondering how you feel about a merge.

**Comment by lucj** [comment]
@geek very sorry for my late reply. I have not done the remaining on my checklist yet. I also need to do some more testing.

**Comment by ptariche** [comment]
Any updates on this pr?

**Comment by Adel-Magebinary** [comment]
Any updates on this pr?

**Comment by geek** [comment]
@Adel-Magebinary no updates at the moment. 

@lucj any thoughts on cutting the backup feature and trimming it down to only updating the versions/new ContainerPilot config?

**Comment by lucj** [comment]
@Adel-Magebinary @geek No update on my side.
No problem, I'll remove the backup and only use last versions of the binaries.

**Pull request merged**
