### PR TITLE
Add consul client as a coprocess to mongo

### PR DESCRIPTION
**Pull request by lucj**
Hello,
I started to embed Consul client in mongodb container as a co-process of mongod.
I'm still working on a problem with the connection to the local consul though.
````
mongodb_1  | Service not registered, registering...
mongodb_1  | 2017/03/06 14:34:40 Service registration failed: Put http://localhost:8500/v1/agent/service/register: dial tcp [::1]:8500: getsockopt: connection refused
````
Regards,
Luc

### CODE REVIEW

**Comment by lucj** [comment]
The local consul agent is not correctly started, I cannot figure out why yet.

When I start it manually from inside the running container with the following command, mongo can register right away.
````
/usr/local/bin/consul agent -data-dir=/opt/consul/data -config-dir=/opt/consul/config -rejoin -retry-join consul
````

**Comment by lucj** [comment]
Seems to work fine switching to ContainerPilot 2.7.0.

**Comment by sberryman** [comment]
What about bumping mongodb to 3.4 as well? It has been out since Nov 29 2016 so quite a long time...

**Comment by sberryman** [comment]
thanks @lucj, that was quick! hopefully joyent will merge and push a new image soon.

**Comment by lucj** [comment]
@sberryman thanks, well spotted. It was planned but then forgotten. I've just changed it.

**Comment by geek** [comment]
LGTM

**Pull request merged**
